language: rust
cache: cargo
os: linux
dist: bionic

jobs:
  include:
    - name: "Linux x86_64 and i686"
      services: docker
      env:
        - CIBW_BUILD="*-manylinux_x86_64 *-manylinux_i686"
    - name: "Linux ARMv8"
      services: docker
      arch: arm64
      env:
        - CIBW_BUILD="*-manylinux_aarch64"
    - name: "macOS"
      os: osx
      osx_image: xcode11

env:
  global:
    # Images
    - CIBW_MANYLINUX_AARCH64_IMAGE="quay.io/pypa/manylinux2014_aarch64"
    - CIBW_MANYLINUX_I686_IMAGE="quay.io/pypa/manylinux2014_i686"
    - CIBW_MANYLINUX_X86_64_IMAGE="quay.io/pypa/manylinux2014_x86_64"

    # Build targeting
    - CIBW_SKIP="cp27-* cp34-* pp*"

    # Build process
    - CIBW_BEFORE_ALL_LINUX="source ./scripts/before_install.sh"
    - CIBW_BEFORE_BUILD="python -m pip install -U pip -r requirements-dev.txt"
    - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin" CARGO_TARGET_DIR="$TRAVIS_BUILD_DIR/target"'

    # Twine
    - TWINE_USERNAME="__token__"

before_install:
    - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
          sudo apt-get -y install python3-pip
      fi

install:
    - |
      python3 -m pip install -U pip setuptools wheel
      python3 -m pip install -U cibuildwheel
      python3 -m pip install -U -r requirements-dev.txt

script:
    - |
      python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  - |
    ls wheelhouse/*.whl
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 setup.py sdist
      pthon3 -m twine upload wheelhouse/*.whl dist/*
    fi
